### ISSUE TITLE
May I translate this checklist into japanese?

### ISSUE THREAD

**Issue by y-takey** [eliotsykes/rails-security-checklist#13]
Thank you for awesome checklist! I'm japanese, I want to share this checklist for japanese rails developers. so, May I translate this awesome checklist into japanese and post it to my blog?

**Comment by eliotsykes** [comment]
Hi @y-takey - thank you for the kind words and offer!

The security checklist is an evolving document that benefits from being community-driven and easy to contribute to.

It'll be a more up-to-date checklist if your translation was kept in a repo on GitHub so it remains easy for the community to contribute to. If you're able to do that then I'd encourage this and you can always post a link to it from your blog.

**Comment by y-takey** [comment]
Thank you for readily agreed. I'll translate the security checklist in a repo on github.

Thanks,

**Comment by eliotsykes** [comment]
That's ace, thank you @y-takey - please share the link to the repo here when you're ready.
