### ISSUE TITLE
Example(s) for SQL injection alert tools?

### ISSUE THREAD

**Issue by jayroh** [eliotsykes/rails-security-checklist#2]
Reading through this (and it's great - so immense thank you's to contributors) and I come to the following

> Web application firewall that can detect, prevent, and alert on known SQL injection attempts

I didn't know this was even "a thing". Are there example tools that would fall under this category that could be included in the document?

Thanks, once again! ⭐

**Comment by eliotsykes** [comment]
Thanks for the kind words @jayroh, so glad you've got something out of it! Thanks for your contribution too, great suggestion 😃

This link to OWASP is a reasonable starting point that links off to a few related resources: https://www.owasp.org/index.php/Web_Application_Firewall - its been added to the checklist.
